services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db_container
    restart: always
    environment:
      MYSQL_DATABASE: 'users'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - mysql_data:/var/lib/mysql
        # Mount the init file into the specific entrypoint directory
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

volumes:
  mysql_data: